### ISSUE TITLE
Wrong License value in package.json

### ISSUE THREAD

**Issue by rondonjon** [leny/react-use-storage#245]
It seems that you're intending to license under [The Unlicense](https://spdx.org/licenses/Unlicense.html), but the SPDX short code for that is `UNLICENSE`.

You're using `UNLICENSED`, which means your project [isn't licensed at all](https://stackoverflow.com/a/35069236/2143524).

**Comment by broofa** [comment]
Bump.  Would love to use this package, but the lack of clear licensing information is offputting.

**Comment by leny** [comment]
Done. Thanks for pointing it.
